export const mockedDraftFlows = {
  draftFlows: {
    drafts: [
      {
        draftId: 88,
        flowName: "Rich",
        flowFileName: "F:\\Connections\\Drafts\\drafts\\Rich.draft",
        subFolder: "drafts",
        flowVersion: "1.0.1.5",
        basedOnLiveVersion: "1.0.1.5",
        createdBy: "iliaM",
        createdOn: "2024-04-19T12:50:58.387",
        updatedBy: "iliaM",
        updatedOn: "2024-06-17T16:44:07.017",
        approved: true,
        approvedBy: "iliaM",
        isDropdownVisible: false,
      },
      {
        draftId: 107,
        flowName: "Stress Test",
        flowFileName: "F:\\Connections\\Drafts\\drafts\\Stress Test.draft",
        subFolder: "drafts",
        flowVersion: "1.0.0.7",
        basedOnLiveVersion: "",
        createdBy: "iliaM",
        createdOn: "2024-06-28T10:50:51.783",
        updatedBy: "iliaM",
        updatedOn: "2024-07-01T10:07:35.72",
        approved: false,
        approvedBy: "",
        isDropdownVisible: false,
      },
    ],
    drafts2: [
      {
        draftId: 106,
        flowName: "New Flow",
        flowFileName: "F:\\Connections\\Drafts\\drafts2\\New Flow.draft",
        subFolder: "drafts2",
        flowVersion: "1.0.0.2",
        basedOnLiveVersion: "",
        createdBy: "iliaM",
        createdOn: "2024-06-14T12:59:19.923",
        updatedBy: "ChrisW",
        updatedOn: "2024-06-27T10:41:46.517",
        approved: false,
        approvedBy: "",
        isDropdownVisible: false,
      },
    ],
  },
};
